<?php
/*
Written by pektsekye@gmail.com on Wednesday Jul 29  2009
version 4.0
*/
$request = $this->getRequest();
$module = $request->getModuleName() .'_'. $request->getControllerName() .'_'. $request->getActionName();
$resource = Mage::getSingleton('core/resource');
$read= $resource->getConnection('core_read');
$ymmTable = $resource->getTableName('ymm');

$select = $read->select()
						->distinct()
						->from($ymmTable,array('make','model','year_bof','year_eof'))
						->where('make != ?','')
						->where('model != ?','')
						->where('year_bof != ?',0)
						->where('year_eof != ?',0)
						->order(array('make', 'model', 'year_bof', 'year_eof')) ;
   
$rows = $read->fetchAll($select);
			
if (count($rows) > 0) {
  
	$Make_array[] = array('id' => 'all', 'text' => 'Choose Vehicle');
	$Model_array[] = array('id' => 'all', 'text' => 'Choose Model');
	$Year_array[] = array('id' => 0, 'text' => 'Choose Year');

   $javascript = '<script language="javascript" type="text/javascript">
var a = new Array();
var b = new Array();
var c = new Array();';

	$y = array();
	$M_a = array();
	$make_old = '';
	$model_old = ''; 
	
	foreach ($rows as $r) {
			
			if (!isset($M_a [$r['make']]))
				$Make_array[] = array('id' => $r['make'], 'text' => $r['make']);

			if (!isset($M_a [$r['make']][$r['model']]) && count($y) > 0){
				$M_a [$make_old][$model_old]=$y;
				$y = array();
			}
			
			if ($r['year_bof'] != 0 && $r['year_eof'] != 0){
				if ($r['year_bof']  == $r['year_eof']){
					$y [$r['year_bof']] = 1;
				} elseif ($r['year_bof']  < $r['year_eof']){	
					while ($r['year_bof'] <= $r['year_eof']){
						$y [$r['year_bof']] = 1;
						$r['year_bof']++;
					}
				}
			}
			$make_old = $r['make'];
			$model_old = $r['model'];
			$M_a [$r['make']][$r['model']] = array();
	}

	$M_a [$make_old][$model_old]=$y;
		

		
	$i = 0;	
	foreach ($M_a as $k =>$v){
		$javascript .= 'a['.$i.']="'.$k.'";b['.$i.']=new Array(';
			$ii = 0;
			$s = '';
			foreach ($M_a[$k] as $kk =>$vv){
				$javascript .= ($ii != 0 ? ',' : '').'"'.$kk.'"';
				$ss = '';
				$iii = 0;
				foreach ($M_a[$k][$kk] as $kkk => $vvv){
					$ss .= ($iii != 0 ? ',' : '').$kkk;
					$iii++;
				}
				if ($iii == 1)
					$ss = '"'.$ss.'"';
				$s .= 'c['.$i.']['.$ii.']=new Array('.$ss.');';
				$ii++;	
			}
		$javascript .= ');c['.$i.']=new Array();'.$s;	
		$i++;	
	}	
	
      $javascript .= '
function pop_model(){
	
	var o ="<select name=\"Model\" onChange=\"pop_year();\" style=\"width: 100%\"><option value=\"all\">Choose Model</option>";	
	var sv = document.make_model_year.Make.value;
	if(sv != "all"){
		var v = a.length;
		while(v--) if(sv == a[v]) break;
		for(var i = 0; i < b[v].length; i++)
		  o+="<option value=\""+b[v][i]+"\">"+b[v][i]+"</option>";
	}
	o+="</select>";
	document.getElementById("model_select").innerHTML= o;
    document.getElementById("year_select").innerHTML= "<select name=\"Year\" style=\"width: 100%\"><option value=\"0\">Choose Year</option></select>";
}
function pop_year(){
	
	var o ="<select name=\"Year\" style=\"width: 100%\" onChange=\"document.make_model_year.submit();\"><option value=\"0\">Choose Year</option>";
	var sv = document.make_model_year.Make.value;
	if(sv != "all"){
		var v = a.length;
		while(v--) if(sv == a[v]) break;
		var sv2 = document.make_model_year.Model.value;
			if(sv2 != "all"){
				var v2 = b[v].length;
				while(v2--) if(sv2 == b[v][v2]) break;	
				for(var i = 0; i < c[v][v2].length; i++)
					o+="<option value=\""+c[v][v2][i]+"\">"+c[v][v2][i]+"</option>";
			}
	}
	o+="</select>";
	document.getElementById("year_select").innerHTML= o;
}
</script>';

	$expire = time()+60*60*24*90;
	
	if (isset($_GET['Make'])){
		setcookie("Make_selected", $_GET['Make'], $expire,'/');
		if ($_GET['Make'] != 'all')
			$Make_selected_var = $_GET['Make'];
	} elseif (isset($_COOKIE['Make_selected']) && $_COOKIE['Make_selected'] != 'all')	
		$Make_selected_var = $_COOKIE['Make_selected'];
		
	if (isset($_GET['Model'])){
		setcookie("Model_selected", $_GET['Model'], $expire,'/'); 
		if ($_GET['Model'] != 'all')
			$Model_selected_var = $_GET['Model'];
	} elseif (isset($_COOKIE['Model_selected']) && $_COOKIE['Model_selected'] != 'all')
		$Model_selected_var = $_COOKIE['Model_selected'];
		
	if (isset($_GET['Year'])){
		setcookie("Year_selected", $_GET['Year'], $expire,'/');
		if ($_GET['Year'] != 0)
			$Year_selected_var = $_GET['Year'];
	} elseif (isset($_COOKIE['Year_selected']) && $_COOKIE['Year_selected'] != 0)
		$Year_selected_var = $_COOKIE['Year_selected'];

    if (isset($Make_selected_var) && isset($M_a[$Make_selected_var]))
      foreach ($M_a[$Make_selected_var] as $k => $v)
		$Model_array[] = array('id' => $k, 'text' => $k);
	if (isset($Make_selected_var) && isset($Model_selected_var) && isset($M_a[$Make_selected_var][$Model_selected_var]))
      foreach ($M_a[$Make_selected_var][$Model_selected_var] as $k => $v)
		$Year_array[] = array('id' => $k, 'text' => $k);
		
	echo $javascript;
	
?>
<div class="box base-mini mini-poll">
    <div class="head">
        <h4><span><?php echo $this->__('Select Vehicle') ?></span></h4>
    </div>
    <form name="make_model_year"  action="<?php 
	$hidden = '';
	if($module == 'catalog_category_view'){
		echo '';
	} elseif ($module == 'catalogsearch_result_index' && Mage::getStoreConfig('catalog/search/filtering', Mage::app()->getStore()->getStoreId())){
		$hidden = '<input type="hidden" name="q" value="' . $request->getParam('q')  . '">';
	}	else {
		echo Mage::getUrl('ymm/product/list');
	}	

?>" method="get">
<?php echo $hidden; ?>
        <div class="content">
			<select name="Make" onChange="pop_model();"  style="width: 100%">
			<?php
			foreach($Make_array as $option)
				echo '<option value="'.$option['id'].'" '.(isset($Make_selected_var) && $Make_selected_var == $option['id'] ? 'SELECTED' : '').'>'.$option['text'].'</option>';
			?>
			</select><br><br>
			<span id="model_select">
			<select name="Model" onChange="pop_year();" style="width: 100%">
			<?php
			foreach($Model_array as $option)
				echo '<option value="'.$option['id'].'" '.(isset($Model_selected_var) && $Model_selected_var == $option['id'] ? 'SELECTED' : '').'>'.$option['text'].'</option>';
			?>
			</select></span><br><br>
			<span id="year_select">
			<select name="Year" onChange="document.make_model_year.submit();"  style="width: 100%">
			<?php
			foreach($Year_array as $option)
				echo '<option value="'.$option['id'].'" '.(isset($Year_selected_var) && $Year_selected_var == $option['id'] ? 'SELECTED' : '').'>'.$option['text'].'</option>';
			?>
			</select></span><br><br>			
        </div>
        <div class="actions">
		<button class="form-button-alt right" type="submit"><span><?php echo $this->__('Go') ?></span></button>
		<?php if(isset($Make_selected_var)): ?>
			<a href="<?php 	
				if($module == 'catalog_category_view'){
					echo '?';
				} elseif ($module == 'catalogsearch_result_index' && Mage::getStoreConfig('catalog/search/filtering', Mage::app()->getStore()->getStoreId())){
					echo '?q=' . $request->getParam('q') . '&';
				}	else {
					echo Mage::getBaseUrl() . '?';
				}	
			?>Make=all&Model=all&Year=0">Clear Vehicle</a>&nbsp;&nbsp;&nbsp;&nbsp;
		<?php endif ?>
		</div>
    </form>
</div>	
<?php
}
?>
