<?php
/*
Written by pektsekye@gmail.com on Monday Jul 20  2009
version 1.0
*/

$resource = Mage::getSingleton('core/resource');
$read= $resource->getConnection('core_read');
$ymmTable = $resource->getTableName('ymm');

$select = $read->select()
						->distinct()
						->from($ymmTable,array('products_car_make','products_car_model','products_car_year_bof','products_car_year_eof'))
						->where('products_car_make != ?','')
						->where('products_car_model != ?','')
						->where('products_car_year_bof != ?',0)
						->where('products_car_year_eof != ?',0)
						->order(array('products_car_make', 'products_car_model', 'products_car_year_bof', 'products_car_year_eof')) ;
   
$rows = $read->fetchAll($select);
			
if (count($rows) > 0) {
  
	$Make_array[] = array('id' => 'all', 'text' => 'Choose Vehicle');
	$Model_array[] = array('id' => 'all', 'text' => 'Choose Model');
	$Year_array[] = array('id' => 0, 'text' => 'Choose Year');

   $javascript = '<script language="javascript" type="text/javascript">
var a = new Array();
var b = new Array();
var c = new Array();';

	$y = array();
	$M_a = array();
	$products_car_make_old = '';
	$products_car_model_old = ''; 
	
	foreach ($rows as $Makes) {
		
			if (!isset($M_a [$Makes['products_car_make']]))
				$Make_array[] = array('id' => $Makes['products_car_make'], 'text' => $Makes['products_car_make']);

						
			if (!isset($M_a [$Makes['products_car_make']][$Makes['products_car_model']]) && count($y) > 0){
				$M_a [$products_car_make_old][$products_car_model_old]=$y;
				$y = array();
			}
			
			if ($Makes['products_car_year_bof'] != 0 && $Makes['products_car_year_eof'] != 0){
				if ($Makes['products_car_year_bof']  == $Makes['products_car_year_eof']){
					$y [$Makes['products_car_year_bof']] = 1;
				} elseif ($Makes['products_car_year_bof']  < $Makes['products_car_year_eof']){	
					while ($Makes['products_car_year_bof'] <= $Makes['products_car_year_eof']){
						$y [$Makes['products_car_year_bof']] = 1;
						$Makes['products_car_year_bof']++;
					}
				}
			}
			$products_car_make_old = $Makes['products_car_make'];
			$products_car_model_old = $Makes['products_car_model'];
			$M_a [$Makes['products_car_make']][$Makes['products_car_model']] = array();
	}

	$M_a [$products_car_make_old][$products_car_model_old]=$y;
		

		
	$i = 0;	
	foreach ($M_a as $k =>$v){
		$javascript .= 'a['.$i.']="'.$k.'";b['.$i.']=new Array(';
			$ii = 0;
			$s = '';
			foreach ($M_a[$k] as $kk =>$vv){
				$javascript .= ($ii != 0 ? ',' : '').'"'.$kk.'"';
				$ss = '';
				$iii = 0;
				foreach ($M_a[$k][$kk] as $kkk => $vvv){
					$ss .= ($iii != 0 ? ',' : '').$kkk;
					$iii++;
				}
				if ($iii == 1)
					$ss = '"'.$ss.'"';
				$s .= 'c['.$i.']['.$ii.']=new Array('.$ss.');';
				$ii++;	
			}
		$javascript .= ');c['.$i.']=new Array();'.$s;	
		$i++;	
	}	
	
      $javascript .= '
function pop_model(){
	
	var o ="<select name=\"Model\" onChange=\"pop_year();\" style=\"width: 100%\"><option value=\"all\">Choose Model</option>";	
	var sv = document.make_model_year.Make.value;
	if(sv != "all"){
		var v = a.length;
		while(v--) if(sv == a[v]) break;
		for(var i = 0; i < b[v].length; i++)
		  o+="<option value=\""+b[v][i]+"\">"+b[v][i]+"</option>";
	}
	o+="</select>";
	document.getElementById("model_select").innerHTML= o;
    document.getElementById("year_select").innerHTML= "<select name=\"Year\" style=\"width: 100%\"><option value=\"0\">Choose Year</option></select>";
}
function pop_year(){
	
	var o ="<select name=\"Year\" style=\"width: 100%\" onChange=\"document.make_model_year.submit();\"><option value=\"0\">Choose Year</option>";
	var sv = document.make_model_year.Make.value;
	if(sv != "all"){
		var v = a.length;
		while(v--) if(sv == a[v]) break;
		var sv2 = document.make_model_year.Model.value;
			if(sv2 != "all"){
				var v2 = b[v].length;
				while(v2--) if(sv2 == b[v][v2]) break;	
				for(var i = 0; i < c[v][v2].length; i++)
					o+="<option value=\""+c[v][v2][i]+"\">"+c[v][v2][i]+"</option>";
			}
	}
	o+="</select>";
	document.getElementById("year_select").innerHTML= o;
}
</script>';

	if (isset($_GET['Make'])){
		if($_GET['Make'] != 'all')
			$Make_selected_var = $_GET['Make'];
	} elseif (isset($_COOKIE['Make_selected']) && $_COOKIE['Make_selected'] != 'all')	
		$Make_selected_var = $_COOKIE['Make_selected'];
		
	if (isset($_GET['Model'])){
		if($_GET['Model'] != 'all')
			$Model_selected_var = $_GET['Model'];
	} elseif (isset($_COOKIE['Model_selected']) && $_COOKIE['Model_selected'] != 'all')
		$Model_selected_var = $_COOKIE['Model_selected'];
		
	if (isset($_GET['Year'])){
		if($_GET['Year'] != 0)
			$Year_selected_var = $_GET['Year'];
	} elseif (isset($_COOKIE['Year_selected']) && $_COOKIE['Year_selected'] != 0)
		$Year_selected_var = $_COOKIE['Year_selected'];

    if (isset($Make_selected_var) && isset($M_a[$Make_selected_var]))
      foreach ($M_a[$Make_selected_var] as $k => $v)
		$Model_array[] = array('id' => $k, 'text' => $k);
	if (isset($Make_selected_var) && isset($Model_selected_var) && isset($M_a[$Make_selected_var][$Model_selected_var]))
      foreach ($M_a[$Make_selected_var][$Model_selected_var] as $k => $v)
		$Year_array[] = array('id' => $k, 'text' => $k);
		
	echo $javascript;
	
?>
<div class="box base-mini mini-poll">
    <div class="head">
        <h4><span><?php echo $this->__('Select Vehicle') ?></span></h4>
    </div>
    <form name="make_model_year"  method="get">
        <div class="content">
			<select name="Make" onChange="pop_model();"  style="width: 100%">
			<?php
			foreach($Make_array as $option)
				echo '<option value="'.$option['id'].'" '.(isset($Make_selected_var) && $Make_selected_var == $option['id'] ? 'SELECTED' : '').'>'.$option['text'].'</option>';
			?>
			</select><br><br>
			<span id="model_select">
			<select name="Model" onChange="pop_year();" style="width: 100%">
			<?php
			foreach($Model_array as $option)
				echo '<option value="'.$option['id'].'" '.(isset($Model_selected_var) && $Model_selected_var == $option['id'] ? 'SELECTED' : '').'>'.$option['text'].'</option>';
			?>
			</select></span><br><br>
			<span id="year_select">
			<select name="Year" onChange="document.make_model_year.submit();"  style="width: 100%">
			<?php
			foreach($Year_array as $option)
				echo '<option value="'.$option['id'].'" '.(isset($Year_selected_var) && $Year_selected_var == $option['id'] ? 'SELECTED' : '').'>'.$option['text'].'</option>';
			?>
			</select></span><br><br>			
        </div>
        <div class="actions">
		<button class="form-button-alt right" type="submit"><span><?php echo $this->__('Go') ?></span></button>
		<a href="?Make=all&Model=all&Year=0">Clear Vehicle</a>&nbsp;&nbsp;&nbsp;&nbsp;
		</div>
    </form>
</div>	
<?php
}
?>
